sudo: required
services:
  - docker

before_install:
  - docker build -t jaxov/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jaxov/client-test yarn test -- --coverage

after_success:
  - docker build -t jaxov/client ./client
  - docker build -t jaxov/nginx ./nginx
  - docker build -t jaxov/server ./server
  - docker build -t jaxov/worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jaxov/client
  - docker push jaxov/nginx
  - docker push jaxov/server
  - docker push jaxov/worker
